---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: graphanacloud-secret
  namespace: grafana
spec:
  encryptedData:
    token: AgBaXBpmqpSBoHje9tIQ4UQPoSkoHKoPH3fGXibPCmC+fe0ATg/FdeiHLRnknOq6n83lCvvaHtQAN2GrhhUAzg7WzrlCak/SlXUb6q+l+ghrbELke1lViraIKLl7uZYFTorvL085t5ze90Fanimn8k66Yu3GIbBAGHt1k5wK37W3XPcyEqBCK2SAjU6I+odLI/z0UM60/CncPDPUE7ZgUdlaScHEJLg2GQKs4OMih16d3rjziw3WqRu/eCqxEUi2Czglm+NvTJLapQZRcCZRgETHPwQ+3QeEIhORNr+bcaS0rp+q4SztJZnjcLiIRiBV2SFY967zFB23oCEncjNHOFRxdWjXQi83iWvojhAxmzy0N/W5Fi4V3jWlb3fKcMriluBX5yuL3+23nQya9nNrzcpvREpwoUdRaeUjJor2lCCJyshFK2REQiQdh5UVZSVEp/WKLWmu4v+wr32UixMyuvV1z8bQC23xq3csBIJ09yEBVsXViwJpGHj3KMSX4BTvAihHD5nnqutQu/P6DS+oe420kUCwO9QctmZgqOOdOomTJxmE5KiXdCa3EcADcx/Q/VA93w6CzFQ6NdDn20kjcxiDe3cgS5kTCdvQ7J6NMo2pVkKLInsa/9dtFP7gycRLQwUOM877WeqYJBmtPmOpH68OzBTVopIVa8Pb4Q+prnhPLWoANM7JOz27P/cXR8zwMyHe/iB/eAQV/Q6Bh4kkSF5AmVza7C9gp2kfaRdNZ558OLVWrJOzGgahLX5on3scQkKZT58Jh4tzwKXJL0Zbi/mpPd8yup0CkMDT8hQwPHXv/t3TSgh9WAfCL989nqm6irYrketwLSoyXKZZCwvoHEJo2cjAy5cDK+Pwgk/NpOtVWnPtESpQTdRf+7MiKizqPFgp0I1VU+LbMnuMpAmMFM6OAmlEC+Akdg6S7BoP
  template:
    metadata:
      creationTimestamp: null
      name: graphanacloud-secret
      namespace: grafana
    type: Opaque